gg:
  jte:
    development-mode: true
    use-precompiled-templates: false
    template-location: apps/web/src/main/jte

spring:
  config:
    import: optional:secrets.yml
  application:
    name: groceryPriceChecker-web
  datasource:
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
  devtools:
    restart:
      enabled: true
  session:
    jdbc:
      cleanup-cron: "0 0 * * * *"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
