gg:
  jte:
    development-mode: true

spring:
  application:
    name: groceryPriceChecker
  datasource:
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
  devtools:
    restart:
      enabled: true
