server:
  port: 8090

spring:
  application:
    name: groceryPriceChecker-scrapper
  datasource:
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
  devtools:
    restart:
      enabled: true